### ISSUE TITLE
how can I stop the download task?

### ISSUE THREAD

**Issue by sigarron** [gegis/smart-downloader#1]
how can I stop the download task?

**Comment by sigarron** [comment]
hi, 
thanks for u reply,  I implement a download manager in ElectronJS with smart-downloader, so it needs a feature to pausing(stop) a task and resume.

**Comment by gegis** [comment]
Hi,
Okay, I will look into implementing this as soon as I can @1week. I think it's useful to have. Building on Electron - as it's cross-platform, please be careful that operating system must have wget working, I haven't had time to implement a fall back for operating systems that don't support wget, or on windows I believe it's possible to use executable wget. And for the fall back option - I haven't found a module that could support download throttle speed and be resumable...

**Comment by gegis** [comment]
Hi,
I've just published 1.2.1 version, from this version you should be able now to stop ("pause") the download process, you can find example in readme file, or here:
```
const SmartDownloader = require('smart-downloader');

const downloader = new SmartDownloader();

// It returns child process instance
const cmd = downloader.download({
    uri: 'https://unsplash.com/photos/cvBBO4PzWPg/download?force=true',
    destinationDir: './downloads/',
    destinationFileName: 'test-stop.jpg,
    downloadSpeedLimit: 300
}, (err, data) => {

    if (err) {

        // Handling the known error
        if (err.message === 'Download error. Signal: SIGTERM') {

            console.log('Handled stop);
        } else {

            console.log(err);
        }
    }
    console.log(data);
});

// After 3 seconds we decide we want to stop it from downloading
setTimeout(() => {

    // You can kill it with custom signal, i.e. "SIGINT"
    // By default it's SIGTERM signal
    // It will cause an error in your callback, make sure to handle it
    cmd.kill();
}, 3000);
```

Please let me know, if that works for you.

**Comment by sigarron** [comment]
it's awesome, you are amazing buddy.
i'll reply u back, if there any problem. thank u.

**Comment by gegis** [comment]
Hi, have you had a chance to test? Can I close this issue now?

**Comment by gegis** [comment]
Hi, I haven't heard for a while.
Closing this issue.

**Comment by sigarron** [comment]
sorry for the reply late.   it's works fine,  thank you very much.
